module.exports = {
	MODELS: [
		{ id: 'Auto', label: 'Auto Detect' },
		{ id: 'Air Fly', label: 'Air Fly' },
		{ id: 'Air Fly Pro', label: 'Air Fly Pro' },
		{ id: 'Air Fly Pro (2019)', label: 'Air Fly Pro (2019)' },
		{ id: 'C10', label: 'C10' },
		{ id: 'C15', label: 'C15' },
		{ id: 'C25', label: 'C25' },
		{ id: 'C90R', label: 'C90R' },
		{ id: 'CCU', label: 'CCU' },
		{ id: 'Color Fly', label: 'Color Fly' },
		{ id: 'Color Fly (2020)', label: 'Color Fly (2020)' },
		{ id: 'CuePilot Panel', label: 'CuePilot Panel' },
		{ id: 'Dream Key Duo', label: 'Dream Key Duo' },
		{ id: 'Dream Key Uno', label: 'Dream Key Uno' },
		{ id: 'ETH-GPI Link', label: 'ETH-GPI Link' },
		{ id: 'Hawk Eye Innovations Replay', label: 'Hawk Eye Innovations Replay' },
		{ id: 'Inline 10', label: 'Inline 10' },
		{ id: 'Inline 22', label: 'Inline 22' },
		{ id: 'Inline 22 (2020)', label: 'Inline 22 (2020' },
		{ id: 'Live Fly', label: 'Live Fly' },
		{ id: 'Master Key 36', label: 'Master Key 36' },
		{ id: 'Master Key One', label: 'Master Key One' },
		{ id: 'Micro Fly', label: 'Micro Fly' },
		{ id: 'Micro GPIO', label: 'Micro GPIO' },
		{ id: 'Micro Tally', label: 'Micro Tally' },
		{ id: 'Mini Fly', label: 'Mini Fly' },
		{ id: 'MK48', label: 'MK48' },
		{ id: 'MKA1', label: 'MKA1' },
		{ id: 'MKA2', label: 'MKA2' },
		{ id: 'MKA3', label: 'MKA3' },
		{ id: 'MKA4', label: 'MKA4' },
		{ id: 'MKT1', label: 'MKT1' },
		{ id: 'PTZ Extreme', label: 'PTZ Extreme' },
		{ id: 'PTZ Extreme (2020)', label: 'PTZ Extreme (2020)' },
		{ id: 'PTZ Fly', label: 'PTZ Fly' },
		{ id: 'PTZ Live', label: 'PTZ Live' },
		{ id: 'PTZ Pro', label: 'PTZ Pro' },
		{ id: 'PTZ Pro (2020)', label: 'PTZ Pro (2020)' },
		{ id: 'PTZ Wiz', label: 'PTZ Wiz' },
		{ id: 'PTZ Wiz (2020)', label: 'PTZ Wiz (2020)' },
		{ id: 'Quick Bar', label: 'Quick Bar' },
		{ id: 'Quick Pad', label: 'Quick Pad' },
		{ id: 'Rack Control Duo', label: 'Rack Control Duo' },
		{ id: 'Rack Control XK-1', label: 'Rack Control XK-1' },
		{ id: 'Rack Control XK-2', label: 'Rack Control XK-2' },
		{ id: 'Rack Fly Duo', label: 'Rack Fly Duo' },
		{ id: 'Rack Fly Duo X', label: 'Rack Fly Duo X' },
		{ id: 'Rack Fly Trio', label: 'Rack Fly Trio' },
		{ id: 'Rack Fly Uno', label: 'Rack Fly Uno' },
		{ id: 'Rack Fusion I', label: 'Rack Fusion I' },
		{ id: 'Rack Fusion II', label: 'Rack Fusion II' },
		{ id: 'Rack Fusion Live', label: 'Rack Fusion Live' },
		{ id: 'RCP', label: 'RCP' },
		{ id: 'RCP Mini', label: 'RCP Mini' },
		{ id: 'RCP Mini Pro', label: 'RCP Mini Pro' },
		{ id: 'RCPV2', label: 'RCPV2' },
		{ id: 'SDI-GPI Link', label: 'SDI-GPI Link' },
		{ id: 'Smart Switch Test Controller', label: 'Smart Switch Test Controller' },
		{ id: 'Sobey AUX Board', label: 'Sobey AUX Board' },
		{ id: 'Sobey ME board', label: 'Sobey ME board' },
		{ id: 'Sobey Multi Function Block Zero', label: 'Sobey Multi Function Block Zero' },
		{ id: 'Sobey Transition Block', label: 'Sobey Transition Block' },
		{ id: 'Tally Box', label: 'Tally Box' },
		{ id: 'Wave Board', label: 'Wave Board' },
		{ id: 'XC1', label: 'XC1' },
		{ id: 'XC2', label: 'XC2' },
		{ id: 'XC3', label: 'XC3' },
		{ id: 'XC4', label: 'XC4' },
		{ id: 'XC5', label: 'XC5' },
		{ id: 'XC6', label: 'XC6' },
		{ id: 'XC7', label: 'XC7' },
		{ id: 'XC8', label: 'XC8' },
		{ id: 'XC9', label: 'XC9' },
		{ id: 'XC10', label: 'XC10' },
		{ id: 'XC11', label: 'XC11' },
		{ id: 'XC12', label: 'XC12' },
		{ id: 'XC13', label: 'XC13' },
		{ id: 'XC14', label: 'XC14' },
		{ id: 'XC15', label: 'XC15' },
		{ id: 'XC16', label: 'XC16' },
		{ id: 'XC17', label: 'XC17' },
		{ id: 'XC18', label: 'XC18' },
		{ id: 'XC19', label: 'XC19' },
		{ id: 'XC20', label: 'XC20' },
		{ id: 'XC21', label: 'XC21' },
		{ id: 'XC22', label: 'XC22' },
		{ id: 'XC23', label: 'XC23' },
		{ id: 'XC25', label: 'XC25' },
		{ id: 'XC24', label: 'XC24' },
		{ id: 'XC7 Standalone', label: 'XC7 Standalone' },
		{ id: 'XC8 Standalone', label: 'XC8 Standalone' },
		{ id: 'XPoint 24', label: 'XPoint 24' },
		{ id: 'XPoint 48', label: 'XPoint 48' },
		{ id: 'Other', label: 'Other Models' },
	],
}
